// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUrClYa6BYbjLJtg_eOBD2i7lwG7W-qxA',
    appId: '1:867623811307:web:c88cc1a1aca35150c426ae',
    messagingSenderId: '867623811307',
    projectId: 'smartcart-cf4ac',
    authDomain: 'smartcart-cf4ac.firebaseapp.com',
    databaseURL: 'https://smartcart-cf4ac-default-rtdb.firebaseio.com',
    storageBucket: 'smartcart-cf4ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhoOaFy0VC90XSWc6Sbql5zakQc_8ezdI',
    appId: '1:867623811307:android:83eec99b76b4e7fac426ae',
    messagingSenderId: '867623811307',
    projectId: 'smartcart-cf4ac',
    databaseURL: 'https://smartcart-cf4ac-default-rtdb.firebaseio.com',
    storageBucket: 'smartcart-cf4ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCPs86uTEqCwIAqj2OpYNfgAN-W0iTPWI',
    appId: '1:867623811307:ios:7186aa3a0f44d0dbc426ae',
    messagingSenderId: '867623811307',
    projectId: 'smartcart-cf4ac',
    databaseURL: 'https://smartcart-cf4ac-default-rtdb.firebaseio.com',
    storageBucket: 'smartcart-cf4ac.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCPs86uTEqCwIAqj2OpYNfgAN-W0iTPWI',
    appId: '1:867623811307:ios:7186aa3a0f44d0dbc426ae',
    messagingSenderId: '867623811307',
    projectId: 'smartcart-cf4ac',
    databaseURL: 'https://smartcart-cf4ac-default-rtdb.firebaseio.com',
    storageBucket: 'smartcart-cf4ac.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUrClYa6BYbjLJtg_eOBD2i7lwG7W-qxA',
    appId: '1:867623811307:web:7e3e9b5f5278cfc4c426ae',
    messagingSenderId: '867623811307',
    projectId: 'smartcart-cf4ac',
    authDomain: 'smartcart-cf4ac.firebaseapp.com',
    databaseURL: 'https://smartcart-cf4ac-default-rtdb.firebaseio.com',
    storageBucket: 'smartcart-cf4ac.firebasestorage.app',
  );

}